
###
POST https://3245-breathecode-pythonflaska-smtgpy2tzyq.ws-us33.gitpod.io/todos
content-type:application/json

{"label":"Another Task",
"done":false
}

###
DELETE https://3245-breathecode-pythonflaska-smtgpy2tzyq.ws-us33.gitpod.io/todos